BEGIN TRY

BEGIN TRAN;

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'settings')
BEGIN
  CREATE TABLE [dbo].[settings] (
    [key]       NVARCHAR(1000) NOT NULL,
    [value]     NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2      NOT NULL CONSTRAINT [settings_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2      NOT NULL,
    CONSTRAINT [settings_pkey] PRIMARY KEY CLUSTERED ([key])
  );
END;

COMMIT TRAN;

END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0 ROLLBACK TRAN;
  THROW;
END CATCH;
